workflows:
  build_ios:
    name: Build FoodTruckSimple (Free Apple ID)
    max_build_duration: 60
    environment:
      vars:
        APP_SCHEME: FoodTruckSimple
        PROJECT_PATH: FoodTruck.xcodeproj
        TEAM_ID: 7AP9L8RUAG
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build IPA
        script: |
          # Архивируем проект
          xcodebuild -project "$PROJECT_PATH" \
                     -scheme "$APP_SCHEME" \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/$APP_SCHEME.xcarchive \
                     clean archive CODE_SIGNING_ALLOWED=YES
          
          # Экспортируем IPA
          xcodebuild -exportArchive \
                     -archivePath build/$APP_SCHEME.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath build
    artifacts:
      - build/*.ipa
